config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  post 'send_email' => 'application'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # default page for the application

  def index

  end
  require 'rest_client'
  require 'json'
  def send_email
    @status = 'OK'
    @errors = false
    begin
      params[:emails].reject! { |c| c.blank? }
      unless params[:emails].blank?
        invalid_emails = (params[:emails] & get_suppressions)
        @errors = "#{invalid_emails.join(',')} are suppressed emails,please remove them from your list" unless invalid_emails.blank?
        unless @errors
          RestClient.post "#{APIURL}messages",
                          :from => 'sudheerm16@gmail.com',
                          :to => params[:emails].join(','),
                          :subject => params[:subject],
                          :text => params[:body],
                          'o:campaign' => "#{params[:campaign_id]}"
          RestClient.post "#{APIURL}messages",
                          :from => 'sudheerm16@gmail.com',
                          :to => 'sudheerm16@gmail.com',
                          :subject => "#{params[:campaign_id]} - Campaign List",
                          :text => "#{params[:emails].join(',')} are the previously send emails"
        end
      else
        @errors = 'Please add at least one email to your list'
      end
    rescue Exception => invalid
      @errors = invalid.message
    end

    respond_to do |format|
      format.js { flash[:notice] = 'Emails sent successfully' }
    end
  end

  def get_suppressions
    JSON.parse(RestClient.get "#{APIURL}complaints")['items'] + JSON.parse(RestClient.get "#{APIURL}bounces")['items'] +
        JSON.parse(RestClient.get "#{APIURL}unsubscribes")['items']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form.html.erb
<%= form_tag(send_email_path,remote: true) do %>
    <div class="form-group">
      <label for="subject">Subject:</label>
      <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required="true">
    </div>
    <div class="form-group">
      <label for="campaign-id">Campaign ID:</label>
      <input type="text" class="form-control" placeholder="Campaign ID" name="campaign_id" id="campaign-id" required="true">
    </div>
    <div class="form-group">
      <label for="body">Body:</label>
      <textarea class="form-control" rows="3" id="body" placeholder="Body" required="true" name="body"></textarea>
    </div>
    <div class="multi-field-wrapper">
      <div class="multi-fields" style="margin-bottom: 10px;">
        <div class="multi-field form-inline" style="margin-bottom: 10px;">
          <input class="form-control" type="email" placeholder="Email" name="emails[]">
          <button type="button" class="btn btn-danger remove-field">Remove</button>
        </div>
      </div>
      <button type="button" class="btn btn-default add-field" style="margin-bottom: 10px;">Add Email</button>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

<script>
    $(function () {
        $('.multi-field-wrapper').each(function () {
            var $wrapper = $('.multi-fields', this);
            $(document).on('click',".add-field",function () {
                $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find('input').val('').focus();
            });
            $(document).on('click',".multi-field .remove-field",function () {
                if ($('.multi-field', $wrapper).length > 1)
                    $(this).parent('.multi-field').remove();
            });
        });
    })
</script>

app/views/application/index.html.erb
<div id="notice" style="color: green"></div>
<div id="email-form">
  <%= render partial: 'form' %>
</div>

app/views/application/send_email.js.erb
<% unless @errors %>
$("#notice").html("<%= flash[:notice] %>");
$('#email-form').html("<%= j render(:partial => 'form') %>");
<% else %>
alert('<%= @errors %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Email Generator" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>

<body>


<div class="container" style="margin-top: 50px;">
  <div class="row">
    <div class="col-lg-12">

      <%= yield %>
    </div>
  </div><!--/row-->
</div> <!-- /container -->

</body>
</html>